# Generated by Django 4.1.5 on 2023-01-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
