# Generated by Django 4.1.5 on 2023-01-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
